### ISSUE TITLE
No output when running psac

### ISSUE THREAD

**Issue by esaliya** [patflick/psac#1]
I was under the assumption that psac would produce the suffix array as output file. Is this true because I only see output similar to the following?

Alphabet: [
,  , ,, ., A, C, D, F, I, O, S, T, V, W, Y, a, b, c, d, e, f, g, h, i, k, l, m, n, o, p, r, s, t, u, v, w, x, y]
Detecting sigma=38 => l=6, k=10
TIMER	1.520e-01	1.520e-01	1.520e-01	1	initial-bucketing
TIMER	1.400e-02	1.400e-02	1.400e-02	2	arr-tupelize
TIMER	3.070e-01	3.070e-01	3.070e-01	2	shift-buckets
TIMER	5.300e-02	5.300e-02	5.300e-02	3	isa2sa_samplesort
TIMER	7.300e-02	7.300e-02	7.300e-02	2	ISA-to-SA
iteration 10: unfinished buckets = 0, unfinished elements = 0
TIMER	1.102e+00	1.102e+00	1.102e+00	2	rebucket
TIMER	5.000e-03	5.000e-03	5.000e-03	2	arr-untupelize
TIMER	7.300e-02	7.300e-02	7.300e-02	2	SA-to-ISA
TIMER	1.699e+00	1.699e+00	1.699e+00	1	construct-msgs
TIMER	1.000e-03	1.000e-03	1.000e-03	1	fix-isa
PSAC time: 2.477e+00 ms

**Comment by patflick** [comment]
Hi @esaliya.

I just pulled in a  lot of changes from the `dev` branch. The `./psac` executable now has a `-o` option for setting output file names.

Please check the updated main readme for an example of how to use it.

Cheers
