### ISSUE TITLE
fatal error: mxx/file.hpp: No such file or directory

### ISSUE THREAD

**Issue by Ansonmy** [patflick/psac#4]
Thank for your sharing,when I follow the Compiling,
I do make ,it's result is ：
#include <mxx/file.hpp>
          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/benchmark_sac.dir/build.make:82: src/CMakeFiles/benchmark_sac.dir/benchmark.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:362: src/CMakeFiles/benchmark_sac.dir/all] Error 2
make: *** [Makefile:171: all] Error 2

I go to the /ext/mxx, it's empty,why is this? could  you help me ? thank you very much

**Comment by patflick** [comment]
Try running:

```
git submodule init
git submodule update
```

Then run `cmake` and `make` again.

**Comment by Ansonmy** [comment]
Yes,it's running correctly following your steps,it helps me  a lot.
thank you very much.Wish you a wonderful Thanksgiving!
